// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erpdmkcehxlxmuuievcb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycGRta2NlaHhseG11dWlldmNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTIyNTQsImV4cCI6MjA2MTM4ODI1NH0.u5xPbb0Cwfs4SZaf4tT-aOUUQLFBXG7GoaTw8UHAkno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);